/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cc970bf7-b70d-48d0-92c3-5a1c1590870f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_brzORy2V2",
    "aws_user_pools_web_client_id": "26t06v86s04qtbfo2c9rdr8np1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://e2yz5uxmm5dwtgksge5rs5blie.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-54usd2fav5ddzpins3rmhk5s3e",
    "aws_user_files_s3_bucket": "imagestore135632-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
